### ISSUE TITLE
[Bug] 0% usage will cause wrong output

### ISSUE THREAD

**Issue by JobberRT** [robscott/kube-capacity#73] opened 2022-11-07 11:01 UTC
Here `kc` set the resources unit:
https://github.com/robscott/kube-capacity/blob/9557a2857fa949de037858bb19b8f37580f16470/pkg/capacity/resources.go#L103-L112

And if the `cpu` or `memory` unit is a blank string(0% usage for example), this code will do the wrong judgement(all the judgement about `Format`, here just a example):
https://github.com/robscott/kube-capacity/blob/9557a2857fa949de037858bb19b8f37580f16470/pkg/capacity/resources.go#L366-L372

Because the value of `cpu` or `memory` is a blank string, so it's type won't be `resource.DecimalSI`, and it will always do the `else` code block. And of couse its calculate progress will be wrong too since the `else` code block will call `formatTomegiBytes` and the unit is not correct:
https://github.com/robscott/kube-capacity/blob/9557a2857fa949de037858bb19b8f37580f16470/pkg/capacity/resources.go#L387-L393

The Wrong output will be like(those red ones):
![image](https://user-images.githubusercontent.com/17498767/200294305-c233ac75-833a-4f14-a2f0-aaebfbfceb21.png)

I will try to fix it and provide a PR, but my skills are not good, will do my best

**Comment by robscott** [comment] 2023-01-19 06:36
Thanks for reporting this! I've been pretty underwater recently but if anyone has time to fix this I'll try to review a PR ASAP.

**Comment by robscott** [comment] 2023-02-16 05:36
Hey @KR411-prog, thanks for volunteering! Appreciate any help with this.

**Comment by KR411-prog** [comment] 2023-02-16 16:24
When I checked the main branch, I dont see this if else condition anymore. I see switch case statement with also default condition check.
https://github.com/robscott/kube-capacity/blob/807764563371f82047bed8f55f5a037aae3e1298/pkg/capacity/resources.go#L395-L409

I also dont find wrong unit in cpu for 0% usage now. 
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/14121261/219426371-c4b7a031-f799-4536-aa29-e52b6c327b7c.png">


Please let me know if this issue reported is still valid.

**Comment by JobberRT** [comment] 2023-02-18 03:49
@KR411-prog @robscott Sorry guys, I was late. Did this issue no longer exist? I've not using `KC` for a long time.

**Comment by KR411-prog** [comment] 2023-02-24 22:12
@JobberRT  I think the issue is no longer valid as the main branch does not seem to have the code anymore.

**Comment by robscott** [comment] 2023-02-24 22:26
Thanks @JobberRT and @KR411-prog, will close this out.

**Closed by robscott** 2023-02-24 22:26 UTC
